### PR TITLE
Added first attempt at releasing macro pad

### PR DESCRIPTION
**Pull request by jdfergusson**
Added first revision of Macro Pad PCB.

image
image
image

Please review for feasibility in the etching/drilling process

### CODE REVIEW

**Comment by tjvr** [comment]
Not an expert, but I do have Anna next to me:

* Anna’s not worried about the number of drill holes. You’ve only got three different drill bit sizes which seems reasonable.
* She says you’ll want to etch out all the drill holes. This makes the bit easier to locate in the hole and is easier than drilling through copper.
* To me the tracks look a bit too close together. While we hopefully documented the etching process, I don’t think we documented its limitations. If we ever get time it would be good to do some test etches to figure out the tolerances! But I do remember having trouble with over- and under-etching, particularly earlier in the week — so I would probably err on the side of caution here.
* I see you’ve included a ground pour: AFAIK no existing design has one (not sure why that is though!).

Presumably you’re planning to use socketed headers with the Pico, so it can be removed?

**Comment by Tetrachloroethene** [comment]
I'll dig out the existing ones at some point to compare but purely from the etching side I think it should be doable, but probably needs a closer eye keeping on it than the others have.

There was a lot of variation between the two years and even just from position within the tank, so it's probably awkward to get solid tolerances.

The biggest issue was if there's a large discrepancy in the area being removed across the board - lots of the problems I remember were from the finer detail being lost while waiting for a larger patch to etch away. That was mostly from waiting for most of the board to etch away though - keeping the ground pour probably actually makes this less of a concern. I could see us losing some of the connections to ground while waiting for the larger spaces for the switches to fully etch away, but I assume that's getting drilled away anyway so could just stop etching earlier
image

Tracks being slightly further apart would definitely make it more consistent, but given the whole etch should be a lot faster with less material being removed we should have a bit finer control over it.

**Comment by jdfergusson** [comment]
Realised you can export the board as an SVG with drill marks in place, so we can use that. I'll need to create separate gerbers to order non-homemade boards, but that's fine.

image

**Comment by jdfergusson** [comment]
From Roger

- Add teardrops
- Add mirrored text for lightbox transparency

**Pull request merged**
